/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MonthlyReleaseNotesRouteImport } from './routes/monthly-release-notes'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FrontendRouteImport } from './routes/frontend'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as BackendRouteImport } from './routes/backend'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MobileIndexRouteImport } from './routes/mobile.index'
import { Route as FrontendIndexRouteImport } from './routes/frontend.index'
import { Route as BackendIndexRouteImport } from './routes/backend.index'
import { Route as MobileRcaReportsRouteImport } from './routes/mobile.rca-reports'
import { Route as MobileProjectDocumentationRouteImport } from './routes/mobile.project-documentation'
import { Route as MobileMediaRouteImport } from './routes/mobile.media'
import { Route as FrontendRcaReportsRouteImport } from './routes/frontend.rca-reports'
import { Route as FrontendProjectDocumentationRouteImport } from './routes/frontend.project-documentation'
import { Route as FrontendMediaRouteImport } from './routes/frontend.media'
import { Route as BackendRcaReportsRouteImport } from './routes/backend.rca-reports'
import { Route as BackendProjectDocumentationRouteImport } from './routes/backend.project-documentation'
import { Route as BackendMediaRouteImport } from './routes/backend.media'

const MonthlyReleaseNotesRoute = MonthlyReleaseNotesRouteImport.update({
  id: '/monthly-release-notes',
  path: '/monthly-release-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontendRoute = FrontendRouteImport.update({
  id: '/frontend',
  path: '/frontend',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendRoute = BackendRouteImport.update({
  id: '/backend',
  path: '/backend',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileIndexRoute = MobileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MobileRoute,
} as any)
const FrontendIndexRoute = FrontendIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FrontendRoute,
} as any)
const BackendIndexRoute = BackendIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackendRoute,
} as any)
const MobileRcaReportsRoute = MobileRcaReportsRouteImport.update({
  id: '/rca-reports',
  path: '/rca-reports',
  getParentRoute: () => MobileRoute,
} as any)
const MobileProjectDocumentationRoute =
  MobileProjectDocumentationRouteImport.update({
    id: '/project-documentation',
    path: '/project-documentation',
    getParentRoute: () => MobileRoute,
  } as any)
const MobileMediaRoute = MobileMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => MobileRoute,
} as any)
const FrontendRcaReportsRoute = FrontendRcaReportsRouteImport.update({
  id: '/rca-reports',
  path: '/rca-reports',
  getParentRoute: () => FrontendRoute,
} as any)
const FrontendProjectDocumentationRoute =
  FrontendProjectDocumentationRouteImport.update({
    id: '/project-documentation',
    path: '/project-documentation',
    getParentRoute: () => FrontendRoute,
  } as any)
const FrontendMediaRoute = FrontendMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => FrontendRoute,
} as any)
const BackendRcaReportsRoute = BackendRcaReportsRouteImport.update({
  id: '/rca-reports',
  path: '/rca-reports',
  getParentRoute: () => BackendRoute,
} as any)
const BackendProjectDocumentationRoute =
  BackendProjectDocumentationRouteImport.update({
    id: '/project-documentation',
    path: '/project-documentation',
    getParentRoute: () => BackendRoute,
  } as any)
const BackendMediaRoute = BackendMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => BackendRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backend': typeof BackendRouteWithChildren
  '/docs': typeof DocsRoute
  '/frontend': typeof FrontendRouteWithChildren
  '/login': typeof LoginRoute
  '/mobile': typeof MobileRouteWithChildren
  '/monthly-release-notes': typeof MonthlyReleaseNotesRoute
  '/backend/media': typeof BackendMediaRoute
  '/backend/project-documentation': typeof BackendProjectDocumentationRoute
  '/backend/rca-reports': typeof BackendRcaReportsRoute
  '/frontend/media': typeof FrontendMediaRoute
  '/frontend/project-documentation': typeof FrontendProjectDocumentationRoute
  '/frontend/rca-reports': typeof FrontendRcaReportsRoute
  '/mobile/media': typeof MobileMediaRoute
  '/mobile/project-documentation': typeof MobileProjectDocumentationRoute
  '/mobile/rca-reports': typeof MobileRcaReportsRoute
  '/backend/': typeof BackendIndexRoute
  '/frontend/': typeof FrontendIndexRoute
  '/mobile/': typeof MobileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/monthly-release-notes': typeof MonthlyReleaseNotesRoute
  '/backend/media': typeof BackendMediaRoute
  '/backend/project-documentation': typeof BackendProjectDocumentationRoute
  '/backend/rca-reports': typeof BackendRcaReportsRoute
  '/frontend/media': typeof FrontendMediaRoute
  '/frontend/project-documentation': typeof FrontendProjectDocumentationRoute
  '/frontend/rca-reports': typeof FrontendRcaReportsRoute
  '/mobile/media': typeof MobileMediaRoute
  '/mobile/project-documentation': typeof MobileProjectDocumentationRoute
  '/mobile/rca-reports': typeof MobileRcaReportsRoute
  '/backend': typeof BackendIndexRoute
  '/frontend': typeof FrontendIndexRoute
  '/mobile': typeof MobileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backend': typeof BackendRouteWithChildren
  '/docs': typeof DocsRoute
  '/frontend': typeof FrontendRouteWithChildren
  '/login': typeof LoginRoute
  '/mobile': typeof MobileRouteWithChildren
  '/monthly-release-notes': typeof MonthlyReleaseNotesRoute
  '/backend/media': typeof BackendMediaRoute
  '/backend/project-documentation': typeof BackendProjectDocumentationRoute
  '/backend/rca-reports': typeof BackendRcaReportsRoute
  '/frontend/media': typeof FrontendMediaRoute
  '/frontend/project-documentation': typeof FrontendProjectDocumentationRoute
  '/frontend/rca-reports': typeof FrontendRcaReportsRoute
  '/mobile/media': typeof MobileMediaRoute
  '/mobile/project-documentation': typeof MobileProjectDocumentationRoute
  '/mobile/rca-reports': typeof MobileRcaReportsRoute
  '/backend/': typeof BackendIndexRoute
  '/frontend/': typeof FrontendIndexRoute
  '/mobile/': typeof MobileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backend'
    | '/docs'
    | '/frontend'
    | '/login'
    | '/mobile'
    | '/monthly-release-notes'
    | '/backend/media'
    | '/backend/project-documentation'
    | '/backend/rca-reports'
    | '/frontend/media'
    | '/frontend/project-documentation'
    | '/frontend/rca-reports'
    | '/mobile/media'
    | '/mobile/project-documentation'
    | '/mobile/rca-reports'
    | '/backend/'
    | '/frontend/'
    | '/mobile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/login'
    | '/monthly-release-notes'
    | '/backend/media'
    | '/backend/project-documentation'
    | '/backend/rca-reports'
    | '/frontend/media'
    | '/frontend/project-documentation'
    | '/frontend/rca-reports'
    | '/mobile/media'
    | '/mobile/project-documentation'
    | '/mobile/rca-reports'
    | '/backend'
    | '/frontend'
    | '/mobile'
  id:
    | '__root__'
    | '/'
    | '/backend'
    | '/docs'
    | '/frontend'
    | '/login'
    | '/mobile'
    | '/monthly-release-notes'
    | '/backend/media'
    | '/backend/project-documentation'
    | '/backend/rca-reports'
    | '/frontend/media'
    | '/frontend/project-documentation'
    | '/frontend/rca-reports'
    | '/mobile/media'
    | '/mobile/project-documentation'
    | '/mobile/rca-reports'
    | '/backend/'
    | '/frontend/'
    | '/mobile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackendRoute: typeof BackendRouteWithChildren
  DocsRoute: typeof DocsRoute
  FrontendRoute: typeof FrontendRouteWithChildren
  LoginRoute: typeof LoginRoute
  MobileRoute: typeof MobileRouteWithChildren
  MonthlyReleaseNotesRoute: typeof MonthlyReleaseNotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/monthly-release-notes': {
      id: '/monthly-release-notes'
      path: '/monthly-release-notes'
      fullPath: '/monthly-release-notes'
      preLoaderRoute: typeof MonthlyReleaseNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frontend': {
      id: '/frontend'
      path: '/frontend'
      fullPath: '/frontend'
      preLoaderRoute: typeof FrontendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend': {
      id: '/backend'
      path: '/backend'
      fullPath: '/backend'
      preLoaderRoute: typeof BackendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/': {
      id: '/mobile/'
      path: '/'
      fullPath: '/mobile/'
      preLoaderRoute: typeof MobileIndexRouteImport
      parentRoute: typeof MobileRoute
    }
    '/frontend/': {
      id: '/frontend/'
      path: '/'
      fullPath: '/frontend/'
      preLoaderRoute: typeof FrontendIndexRouteImport
      parentRoute: typeof FrontendRoute
    }
    '/backend/': {
      id: '/backend/'
      path: '/'
      fullPath: '/backend/'
      preLoaderRoute: typeof BackendIndexRouteImport
      parentRoute: typeof BackendRoute
    }
    '/mobile/rca-reports': {
      id: '/mobile/rca-reports'
      path: '/rca-reports'
      fullPath: '/mobile/rca-reports'
      preLoaderRoute: typeof MobileRcaReportsRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/project-documentation': {
      id: '/mobile/project-documentation'
      path: '/project-documentation'
      fullPath: '/mobile/project-documentation'
      preLoaderRoute: typeof MobileProjectDocumentationRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/media': {
      id: '/mobile/media'
      path: '/media'
      fullPath: '/mobile/media'
      preLoaderRoute: typeof MobileMediaRouteImport
      parentRoute: typeof MobileRoute
    }
    '/frontend/rca-reports': {
      id: '/frontend/rca-reports'
      path: '/rca-reports'
      fullPath: '/frontend/rca-reports'
      preLoaderRoute: typeof FrontendRcaReportsRouteImport
      parentRoute: typeof FrontendRoute
    }
    '/frontend/project-documentation': {
      id: '/frontend/project-documentation'
      path: '/project-documentation'
      fullPath: '/frontend/project-documentation'
      preLoaderRoute: typeof FrontendProjectDocumentationRouteImport
      parentRoute: typeof FrontendRoute
    }
    '/frontend/media': {
      id: '/frontend/media'
      path: '/media'
      fullPath: '/frontend/media'
      preLoaderRoute: typeof FrontendMediaRouteImport
      parentRoute: typeof FrontendRoute
    }
    '/backend/rca-reports': {
      id: '/backend/rca-reports'
      path: '/rca-reports'
      fullPath: '/backend/rca-reports'
      preLoaderRoute: typeof BackendRcaReportsRouteImport
      parentRoute: typeof BackendRoute
    }
    '/backend/project-documentation': {
      id: '/backend/project-documentation'
      path: '/project-documentation'
      fullPath: '/backend/project-documentation'
      preLoaderRoute: typeof BackendProjectDocumentationRouteImport
      parentRoute: typeof BackendRoute
    }
    '/backend/media': {
      id: '/backend/media'
      path: '/media'
      fullPath: '/backend/media'
      preLoaderRoute: typeof BackendMediaRouteImport
      parentRoute: typeof BackendRoute
    }
  }
}

interface BackendRouteChildren {
  BackendMediaRoute: typeof BackendMediaRoute
  BackendProjectDocumentationRoute: typeof BackendProjectDocumentationRoute
  BackendRcaReportsRoute: typeof BackendRcaReportsRoute
  BackendIndexRoute: typeof BackendIndexRoute
}

const BackendRouteChildren: BackendRouteChildren = {
  BackendMediaRoute: BackendMediaRoute,
  BackendProjectDocumentationRoute: BackendProjectDocumentationRoute,
  BackendRcaReportsRoute: BackendRcaReportsRoute,
  BackendIndexRoute: BackendIndexRoute,
}

const BackendRouteWithChildren =
  BackendRoute._addFileChildren(BackendRouteChildren)

interface FrontendRouteChildren {
  FrontendMediaRoute: typeof FrontendMediaRoute
  FrontendProjectDocumentationRoute: typeof FrontendProjectDocumentationRoute
  FrontendRcaReportsRoute: typeof FrontendRcaReportsRoute
  FrontendIndexRoute: typeof FrontendIndexRoute
}

const FrontendRouteChildren: FrontendRouteChildren = {
  FrontendMediaRoute: FrontendMediaRoute,
  FrontendProjectDocumentationRoute: FrontendProjectDocumentationRoute,
  FrontendRcaReportsRoute: FrontendRcaReportsRoute,
  FrontendIndexRoute: FrontendIndexRoute,
}

const FrontendRouteWithChildren = FrontendRoute._addFileChildren(
  FrontendRouteChildren,
)

interface MobileRouteChildren {
  MobileMediaRoute: typeof MobileMediaRoute
  MobileProjectDocumentationRoute: typeof MobileProjectDocumentationRoute
  MobileRcaReportsRoute: typeof MobileRcaReportsRoute
  MobileIndexRoute: typeof MobileIndexRoute
}

const MobileRouteChildren: MobileRouteChildren = {
  MobileMediaRoute: MobileMediaRoute,
  MobileProjectDocumentationRoute: MobileProjectDocumentationRoute,
  MobileRcaReportsRoute: MobileRcaReportsRoute,
  MobileIndexRoute: MobileIndexRoute,
}

const MobileRouteWithChildren =
  MobileRoute._addFileChildren(MobileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackendRoute: BackendRouteWithChildren,
  DocsRoute: DocsRoute,
  FrontendRoute: FrontendRouteWithChildren,
  LoginRoute: LoginRoute,
  MobileRoute: MobileRouteWithChildren,
  MonthlyReleaseNotesRoute: MonthlyReleaseNotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
